default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ruby_api

test:
  <<: *default
  database: ruby_api

production:
  <<: *default
  database: ruby_api
  username: ruby_api
  password: <%= ENV['RUBY_API_DATABASE_PASSWORD'] %>
