default: &default
  adapter: postgresql
  encoding: utf8
  host: ec2-79-125-118-221.eu-west-1.compute.amazonaws.com
  username: olxlvvapmkmshq
  password: de71e9c9b07e59fcf14a8ae97e1c0684107cc4375edacb1c5dba06a387708065

development:
  <<: *default
  database: ddoh86ovaigj22

test:
  <<: *default
  database: ddoh86ovaigj22

production:
  <<: *default
  database: ddoh86ovaigj22
